### ISSUE TITLE
Licensing headers issues in 1.0.0-RC1

### ISSUE THREAD

**Issue by jrudolph** [apache/incubator-pekko-http#237]
- LICENSE is possibly missing 3rd party code licenses due to the number of files with missing headers? Also these 3rd party files files
  - [x] `./http-core/src/main/scala/org/apache/pekko/http/impl/engine/ws/Utf8Decoder.scala` - nothing to do
  - [x] `./http-core/src/main/scala/org/apache/pekko/http/impl/model/parser/StringBuilding.scala` #249
  - [x] `./http-core/src/main/scala/org/apache/pekko/http/impl/engine/http2/util/AsciiTreeLayout.scala` #248
  - [x] SSE #250
    -  `./http-tests/src/test/java/org/apache/pekko/http/javadsl/marshalling/sse/EventStreamMarshallingTest.java` 
    -  `./http-tests/src/test/java/org/apache/pekko/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java`
    -  `./http-core/src/test/java/org/apache/pekko/http/javadsl/model/sse/ServerSentEventTest.java`
    -  `./http-core/src/main/java/org/apache/pekko/http/javadsl/model/sse/ServerSentEvent.java`
    -  `./http-core/src/main/java/org/apache/pekko/http/javadsl/model/headers/LastEventId.java`
  - [x] `./http-core/src/main/scala-2.13-/org/apache/pekko/http/ccompat/CompatImpl.scala` - nothing to do
- These files are missing headers and are of an unknown license
   - [x] `./docs/src/main/paradox/assets/js/scrollToFragment.js` #242
   - [x] `./http-scalafix/scalafix-tests/src/test/scala/org/apache/pekko/http/fix/RuleSuite.scala` #243
- [x] These scripts without license headers can be removed #241
   - `./scripts/authors.pl`
   - `./scripts/authors.scala`
   - `./scripts/commits-for-release-notes.sh`
   - `./scripts/convert_tabs_to_spaces.sh`
   - `./scripts/dos_to_unix.sh`
   - `./scripts/find-javadoc-error.pl`
   - `./scripts/release_stats.sh`
   - `./scripts/remove_trailing_whitespace.sh`
   - `./scripts/build/github-tagging.sh`
- [x] These files seem to have incorrect headers #240
  - `./http/src/main/boilerplate/org/apache/pekko/http/javadsl/server/JavaPathMatchers.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/directives/FormFieldDirectivesInstances.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/directives/ParameterDirectivesInstances.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/util/ApplyConverterInstances.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/util/ConstructFromTupleInstances.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/util/TupleAppendOneInstances.scala.template`
  - `./http/src/main/boilerplate/org/apache/pekko/http/scaladsl/server/util/TupleFoldInstances.scala.template`
- [x] Remove autobahn scripts (not relevant any more, used for some extra validation on old Jenkins) #238
  -  `./http-core/src/test/scripts/autobahn-jenkins/`
- [x] This file (mentioned in license) also has an incorrect header  #246
  - `/http-core/src/main/scala/org/apache/pekko/http/scaladsl/model/DateTime.scala`
-  [x] Add a note explaning what this file is #239
   - `./http-tests/src/test/extra-libs.zip`

**Comment by pjfanning** [comment]
Utf8Decoder was addressed weeks ago using https://github.com/apache/incubator-pekko-http/pull/198/files - I don't why it is listed as an issue for RC1 - see https://github.com/apache/incubator-pekko-http/pull/198
